name: 'pg-formatter-action'
description: 'Reformat PostgreSQL code with pgFormatter'
inputs:
  pattern:
    required: false
    description: >
      Glob pattern that are used to find source files to format. It is
      possible to specify several patterns by putting each on a new line.
    default: |
      **/*.sql
      **/*.plsql
  follow-symbolic-links:
    required: false
    description: >
      Whether to follow symbolic links.
    default: true
  extra-args:
    required: false
    description: >
      Extra arguments to pass to pgFormatter.
    default: -i
runs:
  using: 'node12'
  main: 'dist/index.js'
