name: CI
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Run formatting
        with:
          extra-args: -o test_files/formatted.sql
        uses: ./.
      - name: Commit changes
          uses: stefanzweifel/git-auto-commit-action@v4
          with:
            commit_user_name: 'pgFormatter formatter action'
            commit_message: Apply formatting
            branch: ${{ github.head_ref }}
